version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: all
  settings:
    gosec:
      excludes:
        - G117
        - G703
        - G704
  disable:
    - gochecknoinits
    - goconst
    - gosmopolitan
    - nestif
    - promlinter
    - maintidx
    - cyclop
    - funcorder
    - depguard
    - gocyclo
    - err113
    - errcheck
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - revive
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - testpackage
