{
 "title": "XRay Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "query_result(count_over_time(xray_up[$__range]))"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(count_over_time(xray_up{job=\"$job\"}[$__range]))"
   }
  ]
 },
 "panels": [
  {
   "title": "XRay Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(xray_up{job=~\"$job\"} == 1)"
    }
   ]
  },
  {
   "title": "Real-Time Overview",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "xray_uptime_seconds{job=~\"$job\"}"
    },
    {
     "expr": "sum by (instance) (increase(xray_traffic_downlink_bytes_total{job=~\"$job\",dimension=\"inbound\"}[$__range]))"
    },
    {
     "expr": "sum by (instance) (increase(xray_traffic_uplink_bytes_total{job=~\"$job\",dimension=\"inbound\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Uplink (-) / Downlink (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(xray_traffic_downlink_bytes_total{job=~\"$job\",dimension=\"inbound\"}[5m]))",
     "legendFormat": "Downlink"
    },
    {
     "expr": "sum(irate(xray_traffic_uplink_bytes_total{job=~\"$job\",dimension=\"inbound\"}[5m]))",
     "legendFormat": "Uplink"
    }
   ]
  },
  {
   "title": "XRay Offline",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(xray_up{job=~\"$job\"}) - count(xray_up{job=~\"$job\"} == 1)"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "instance" },
  {
   "title": "Real-Time Detail Overview",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "increase(xray_traffic_downlink_bytes_total{job=~\"$job\"}[$__range])"
    },
    {
     "expr": "increase(xray_traffic_uplink_bytes_total{job=~\"$job\"}[$__range])"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps", "label": "Uplink (-) / Downlink (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(xray_traffic_downlink_bytes_total{job=~\"$job\",dimension=\"inbound\"}[5m]))",
     "legendFormat": "Downlink"
    },
    {
     "expr": "sum(irate(xray_traffic_uplink_bytes_total{job=~\"$job\",dimension=\"inbound\"}[5m]))",
     "legendFormat": "Uplink"
    }
   ]
  },
  {
   "title": "Download Speed of Inbounds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(xray_traffic_downlink_bytes_total{job=~\"$job\",dimension=\"inbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Inbounds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(xray_traffic_uplink_bytes_total{job=~\"$job\",dimension=\"inbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Outbounds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(xray_traffic_downlink_bytes_total{job=~\"$job\",dimension=\"outbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Outbounds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(xray_traffic_uplink_bytes_total{job=~\"$job\",dimension=\"outbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Download Speed of Users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(xray_traffic_downlink_bytes_total{job=~\"$job\",dimension=\"user\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Upload Speed of Users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(xray_traffic_uplink_bytes_total{job=~\"$job\",dimension=\"user\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}